// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQv33rGy64TcM07fhRqsU2uTrcFJHFDV4',
    appId: '1:891082373643:web:9b3988945d6b90c6b5e50e',
    messagingSenderId: '891082373643',
    projectId: 'campuslunch-e5a2c',
    authDomain: 'campuslunch-e5a2c.firebaseapp.com',
    storageBucket: 'campuslunch-e5a2c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKDCWUFphKUMiHZgSCUY7i3jCbIfb7fEM',
    appId: '1:891082373643:android:a9077d61d5d2545ab5e50e',
    messagingSenderId: '891082373643',
    projectId: 'campuslunch-e5a2c',
    storageBucket: 'campuslunch-e5a2c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6UJFbDBNGOBtOAtWGSUa_jkOR0N1MNhA',
    appId: '1:891082373643:ios:3d16d4a025095ebfb5e50e',
    messagingSenderId: '891082373643',
    projectId: 'campuslunch-e5a2c',
    storageBucket: 'campuslunch-e5a2c.firebasestorage.app',
    iosBundleId: 'com.campuslunch.app',
  );
}
